### ISSUE TITLE
Compilation will be broken with the latest QtCreator

### ISSUE THREAD

**Issue by Kakadu** [e4z9/qtcreator-haskell#11]
Something was reorganized in the commit https://github.com/qt-creator/qt-creator/commit/53a151074ad37d12e730fbd85ec0e0675d00f6d0

Just FYI, Maybe I should try to build it from QtCreator 4.4....

**Comment by e4z9** [comment]
Hi,
the code has moved to the Qt Project on http://code.qt.io/cgit/qt-creator/plugin-haskell.git/ . I haven't managed to set up any mirroring or such, so please use that instead.

It is also a submodule of http://code.qt.io/cgit/qt-creator/qtc-super.git/ , which combines a Qt Creator build with some playground projects like this one, without the need to set up the environment or qmake variables correctly.

**Comment by e4z9** [comment]
I've now manually synced github as well

**Comment by Kakadu** [comment]
@e4z9 You can also change repo's description and point out that it is only a mirror and a real repo is somewhere else.
