### ISSUE TITLE
Please, tutorial

### ISSUE THREAD

**Issue by Kakadu** [e4z9/qtcreator-haskell#12]
@e4z9 Can you add a kind of tutorial how to open an existing Stack project or how to invoke code assist? I have found any new gui elements from your haskell plugin. Either it is very unobvious or I compiled it terribly wrong.... (Yes, it is loaded. I checked!)

**Comment by e4z9** [comment]
As you can possibly see from the issues list, the plugin is so far pretty bad in helping you set up things ;)

First of all please make sure that you can build and run your project with stack from the command line. Also run `stack build ghc-mod` in your project directory. For the hover (type + symbol) information, the plugin runs `stack exec ghc-mod -- legacy-interactive` in your project directory.

In Qt Creator, make sure that Tools > Options > Haskell > Stack executable points to the right `stack` executable. To open your Haskell project, open its `.cabal` file (e.g. via File > Open File or Project). The plugin does not provide any code completion yet. It provides highlighting, information tooltips about a symbol (type / location), "Follow Symbol" (F2), and a simple build & run configuration.

To debug parts of what the plugin tries to do (e.g. for the information tool tips), you can set the environment variable `QT_LOGGING_RULES=qtc.haskell.*.debug=true` before starting Qt Creator.

**Comment by Kakadu** [comment]
Oh, it works! Thanks!

**Comment by e4z9** [comment]
Great!
